# 9. Crea un arrays lleno de 1s con una longitud dada por el usuario

In [6]:

import numpy as np
longitud = int(input("pon la longitud del array: "))
array_usuario = np.ones(longitud)
print(array_usuario)


[1. 1. 1. 1. 1. 1.]


10.Cambia la forma del array para que tenga una estructura de tipo (filas, columnas)

In [14]:
import numpy as np
longitud = int(input("pon la longitud del array: "))
array_usuario = np.ones(longitud)
print(array_usuario)
filas=int(input("Dime cuantas filas quieres  "))
columnas = int(input("Dime cuantas colunmas  quieres "))

if filas*columnas==longitud:
    array_usuario = array_usuario.reshape(filas,columnas)
    print(array_usuario)
else:
    print("no se puede crear este array")

[1. 1. 1. 1. 1.]
no se puede crear este array


11.Crea una “matriz identidad” con la misma forma que el array anterior (filas, columnas)

In [16]:
import numpy as np
longitud = int(input("pon la longitud del array: "))
array_usuario = np.ones(longitud)
print(array_usuario)
filas=int(input("Dime cuantas filas quieres  "))
columnas = int(input("Dime cuantas colunmas  quieres "))

if filas*columnas==longitud:
    array_usuario = array_usuario.reshape(filas,columnas)
    matrix_identidad = np.eye(filas,columnas)
    print(array_usuario)
    print(matrix_identidad)
else:
    print("no se puede crear este array")

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


12.Concatena ambas estructuras horizontalmente y verticalmente
(Pista: Investiga el funcionamiento de concatenate() y de vstack() y hstack() de numpy)

In [23]:
import numpy as np
longitud = int(input("pon la longitud del array: "))
array_usuario = np.ones(longitud)
print(array_usuario)
filas=int(input("Dime cuantas filas quieres  "))
columnas = int(input("Dime cuantas colunmas  quieres "))

if filas*columnas==longitud:
    #comprobamos que se pueda crear el array
    array_usuario = array_usuario.reshape(filas,columnas)
    print("Este es tu array\n",array_usuario)
        #creamos un array matiz
    if filas == columnas:
         matrix_identidad = np.eye(filas,columnas)
    #concatenamos los arrays con las funciones concatenate(), vstrack() y con hstack()
         concatenado1 = np.concatenate((array_usuario,matrix_identidad))
         concatenado2 = np.vstack((array_usuario,matrix_identidad))
         concatenado3 = np.hstack((array_usuario,matrix_identidad))
   
         print("Esta es tu matriz |n",matrix_identidad)
         print("Estos son tus arrays concatenados normalmente \n",concatenado1)
         print("Estos son tus arrays concatenados con #vstrack  \n",concatenado2)
         print("Estos son tus arrays concatenados con #hstack  \n",concatenado3)


else:
    print("no se puede crear este array")

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Este es tu array
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Esta es tu matriz |n [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Estos son tus arrays concatenados normalmente 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Estos son tus arrays concatenados con #vstrack  
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Estos son tus arrays concatenados con #hstack  
 [[1. 1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 0. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0. 1. 0.]
 [1. 1. 1. 1. 0. 0. 0. 1.]]
